### PR TITLE
basic ability to convert unions

### PR DESCRIPTION
**Pull request by piranha**
That's a nice project. :)

### CODE REVIEW

**Comment by sansolovyov** [comment]
So I've pushed second commit, which makes you able to have complex nullable types (we have one and it was failing).

**Comment by chetmancini** [comment]
@piranha Thanks for the PR! Sorry just checking it out now. I have a few thoughts:
1) Currently the tests are failing around `optional-key`. Can you patch those up? I suspect that's a good way to go, though I'm not as familiar with Avro in the part of the spec--does having a nullable union imply an optional key?

2) `Cond-pre` is marked as experimental in `schema`. Seems like that's a good direction to go but we might want to mark our sections as such in case it gets changed in a future version.

Appreciate the contributions!

**Comment by sansolovyov** [comment]
Fix the tests! Avro indeed treats `["int", "null"]` as something completely optional - you do not need to supply that key at all, which is replicated by `optional-key` well. I ran into that in my application, and with those changes it's working well.

As for marking... How would you prefer to mark it? I myself think it's not necessary - if schema ever wants `cond-pre` out, they will make it spit warnings probably, as with other deprecated stuff. Even if it's "experimental" - they say "Deprecate s/either in favor of s/cond-pre", so it seems we're pretty safe here. :)

**Comment by chetmancini** [comment]
@piranha thanks again for the PR!

**Comment by sansolovyov** [comment]
Thanks for the library! :-) We're already using that in production. ;)

**Pull request merged**
